# Generated by Django 4.0.1 on 2022-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField()),
                ('donation_status', models.CharField(choices=[('r', 'request'), ('a', 'approved'), ('s', 'successful'), ('x', 'rejected')], default='r', max_length=1)),
                ('recipient_name', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.IntegerField()),
                ('recipient_address', models.CharField(max_length=500)),
                ('donation_title', models.CharField(max_length=100)),
                ('donation_description', models.CharField(max_length=500)),
                ('donation_purpose', models.CharField(max_length=50)),
                ('donation_required_amount', models.IntegerField()),
                ('donation_recieved_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fu_name', models.CharField(max_length=50)),
                ('fu_email', models.EmailField(max_length=254)),
                ('fu_message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=300)),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('user_password', models.CharField(max_length=32)),
            ],
        ),
    ]
