# Generated by Django 4.0.1 on 2022-04-28 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_status', models.CharField(choices=[('r', 'request'), ('a', 'approved'), ('s', 'successful'), ('x', 'rejected')], default='r', max_length=1)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('donation_title', models.CharField(max_length=100)),
                ('donation_description', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=50)),
                ('required_amount', models.IntegerField(default=0)),
                ('recieved_amount', models.IntegerField(default=0)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fu_name', models.CharField(max_length=50)),
                ('fu_email', models.EmailField(max_length=254)),
                ('fu_message', models.CharField(max_length=300)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topdonors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('total_amount', models.IntegerField(null=True)),
                ('updated', models.DateTimeField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('date_and_time', models.DateTimeField(default=datetime.datetime, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
