# Generated by Django 4.0.1 on 2022-04-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='recipient_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='recipient_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='recipient_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='recipient_phone',
            new_name='phone',
        ),
    ]
