# Generated by Django 4.0.1 on 2022-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_rename_recipient_address_donation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_recieved_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recipient_id',
            field=models.IntegerField(null=True),
        ),
    ]
