# Generated by Django 4.0.1 on 2022-04-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_alter_donation_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='donation',
            name='slugs',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
