# Generated by Django 4.0.1 on 2022-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_alter_donation_donation_recieved_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_purpose',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_recieved_amount',
            new_name='recieved_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_required_amount',
        ),
        migrations.AddField(
            model_name='donation',
            name='required_amount',
            field=models.IntegerField(default=0),
        ),
    ]
