# Generated by Django 4.0.1 on 2022-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_donation_image_donation_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
