# Generated by Django 4.0.1 on 2022-04-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_delete_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='recipient_id',
        ),
    ]
