# Generated by Django 4.0.1 on 2022-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_remove_topdonors_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdonors',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topdonors',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
