# Generated by Django 4.0.1 on 2022-05-01 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunding', '0006_topdonors_status_alter_topdonors_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdonors',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.public_donors', verbose_name='unregistered user id'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
    ]
