# Generated by Django 4.0.1 on 2022-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_alter_topdonors_pid_alter_topdonors_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdonors',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
