# Generated by Django 4.0.1 on 2022-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0011_alter_topdonors_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
