# Generated by Django 4.0.1 on 2022-05-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0012_alter_transactions_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('posno', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='topdonors',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.public_donors', verbose_name='unregistered user id'),
        ),
    ]
