# Generated by Django 4.0.1 on 2022-05-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0013_pos_alter_topdonors_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='css_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crowdfunding.public_donors', verbose_name='unregistered user id'),
        ),
    ]
