# Generated by Django 4.0.1 on 2022-05-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0015_alter_pos_css_class_alter_pos_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.donation', verbose_name='Donation id'),
        ),
    ]
