# Generated by Django 4.0.1 on 2022-05-06 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunding', '0016_alter_transactions_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
