# Generated by Django 4.0.1 on 2022-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0017_donation_uid_alter_donation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_status',
            field=models.CharField(choices=[('r', 'requested'), ('a', 'approved'), ('s', 'successful'), ('x', 'rejected')], default='r', max_length=1),
        ),
    ]
