# Generated by Django 4.0.1 on 2022-05-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0018_alter_donation_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdonors',
            name='pos',
            field=models.TextField(null=True),
        ),
    ]
