# Generated by Django 4.0.1 on 2022-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0019_topdonors_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='visibility',
            field=models.CharField(default='yes', max_length=3),
        ),
    ]
