# Generated by Django 4.0.1 on 2022-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0020_transactions_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdonors',
            name='visibility',
            field=models.CharField(default='yes', max_length=3),
        ),
    ]
