# Generated by Django 4.0.1 on 2022-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0021_topdonors_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='slugs',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
